[package]
name = "tkdriverx/knit-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.3.0"
Roact = "roblox/roact@1.4.2"
Component = "sleitnick/component@2.1.0"
Trove = "sleitnick/trove@0.1.3"
Signal = "sleitnick/signal@1.0.1"
Option = "sleitnick/option@1.0.2"
Comm = "sleitnick/comm@0.1.2"
Promise = "evaera/promise@3.1.0"
Timer = "sleitnick/timer@1.0.3"
TableUtil = "sleitnick/table-util@1.1.1"
Symbol = "sleitnick/signal@1.0.1"
Input = "sleitnick/input@1.1.0"
TaskQueue = "sleitnick/task-queue@0.1.0"
Loader = "sleitnick/loader@1.0.2"
Plasma = "evaera/plasma@0.1.0"

[server-dependencies]
Cmdr = "evaera/cmdr@1.8.4"